### ISSUE TITLE
Why the node whose type is ``ARRAY_OF_TABLES`` returns false when call ``isContainNode`` method?

### ISSUE THREAD

**Issue by Yimismi** [johnlcox/toml4j#9]
Why the node whose type is ``ARRAY_OF_TABLES`` returns false when call ``isContainNode`` method?

**Comment by johnlcox** [comment]
It looks like it was just never added to the `isContainerNode` implementation when `ARRAY_OF_TABLES` support was added.

If you wanted to open a PR to add it and a test confirming it works I would take a look at it.

**Comment by Yimismi** [comment]
I have fixed the bug and open a PR :)

**Comment by johnlcox** [comment]
Thanks, I appreciate it. I have merged the fix to master.
